In [6]:
from google.colab import files
uploaded = files.upload()


Saving Data_for_UCI_named.csv to Data_for_UCI_named.csv


In [7]:
import numpy as np
import pandas as pd

path = '/content/Data_for_UCI_named.csv'

data = pd.read_csv(path)
data.head()


tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   tau1    10000 non-null  float64
 1   tau2    10000 non-null  float64
 2   tau3    10000 non-null  float64
 3   tau4    10000 non-null  float64
 4   p1      10000 non-null  float64
 5   p2      10000 non-null  float64
 6   p3      10000 non-null  float64
 7   p4      10000 non-null  float64
 8   g1      10000 non-null  float64
 9   g2      10000 non-null  float64
 10  g3      10000 non-null  float64
 11  g4      10000 non-null  float64
 12  stab    10000 non-null  float64
 13  stabf   10000 non-null  object 
dtypes: float64(13), object(1)
memory usage: 1.1+ MB


In [28]:
#import matplotlib.pyplot as plt
#%matplotlib inline
#data = data.drop('stab', axis = 1)
data['stabf'].value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

In [31]:
x = data.drop(columns=['stabf'])
y = data['stabf']

In [32]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

print('X_train : {}'.format(x_train.shape))
print('y_train : {}'.format(y_train.shape))
print('X_test  : {}'.format(x_test.shape))
print('y_test  : {}'.format(y_test.shape))

X_train : (8000, 12)
y_train : (8000,)
X_test  : (2000, 12)
y_test  : (2000,)


In [33]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(x_train)

x_train_scaled = scaler.transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [34]:
x_train_scaled = pd.DataFrame(x_train_scaled, columns = x_train.columns)
x_test_scaled = pd.DataFrame(x_test_scaled, columns = x_test.columns)

In [37]:
#RF classifier
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state = 1)
#fitting data  on training set
rf.fit(x_train_scaled, y_train)


RandomForestClassifier(random_state=1)

In [38]:
rf_pred = rf.predict(x_test_scaled)

In [39]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, rf_pred)
print('Accuracy: {}'.format(round(accuracy*100), 4))

from sklearn.metrics import recall_score, precision_score, f1_score, confusion_matrix, classification_report

precision = precision_score(y_test, rf_pred, pos_label='stable')
print('Precision: {}'.format(round(precision*100), 2))  

recall = recall_score(y_test, rf_pred, pos_label='stable')
print('Recall: {}'.format(round(recall*100), 2))

f1 = f1_score(y_test, rf_pred, pos_label='stable')
print('F1: {}'.format(round(f1*100), 2))

print('Classification Report:\n', classification_report(y_test,rf_pred, digits =4))

rf_cnf_mat = confusion_matrix(y_test, rf_pred, labels=['unstable', 'stable'])
print('Confusion Matrix:\n', rf_cnf_mat)

Accuracy: 100
Precision: 100
Recall: 100
F1: 100
Classification Report:
               precision    recall  f1-score   support

      stable     0.9986    1.0000    0.9993       712
    unstable     1.0000    0.9992    0.9996      1288

    accuracy                         0.9995      2000
   macro avg     0.9993    0.9996    0.9995      2000
weighted avg     0.9995    0.9995    0.9995      2000

Confusion Matrix:
 [[1287    1]
 [   0  712]]


In [40]:
print("score of training set: {:.3f}".format(rf.score(x_train_scaled, y_train)))
print("score of test set: {:.3f}".format(rf.score(x_test_scaled, y_test)))

score of training set: 1.000
score of test set: 1.000


In [43]:
#ET classifier
from sklearn.ensemble import ExtraTreesClassifier

etc = ExtraTreesClassifier(random_state = 1)
etc.fit(x_train_scaled, y_train)

ExtraTreesClassifier(random_state=1)

In [44]:
etc_pred = etc.predict(x_test_scaled)

In [45]:

etc_accuracy = accuracy_score(y_test, etc_pred)
print('Accuracy: {}'.format(round(etc_accuracy*100), 2))

etc_precision = precision_score(y_test, etc_pred, pos_label='stable')
print('Precision: {}'.format(round(etc_precision*100), 2))  

etc_recall = recall_score(y_test, etc_pred, pos_label='stable')
print('Recall: {}'.format(round(etc_recall*100), 2))

etc_f1 = f1_score(y_test, etc_pred, pos_label='stable')
print('F1: {}'.format(round(etc_f1*100), 2))


print('Classification Report:\n', classification_report(y_test,etc_pred, digits =4))

etc_cnf_mat = confusion_matrix(y_test, etc_pred)
print('Confusion Matrix:\n', etc_cnf_mat)

Accuracy: 98
Precision: 98
Recall: 97
F1: 98
Classification Report:
               precision    recall  f1-score   support

      stable     0.9830    0.9747    0.9788       712
    unstable     0.9861    0.9907    0.9884      1288

    accuracy                         0.9850      2000
   macro avg     0.9845    0.9827    0.9836      2000
weighted avg     0.9850    0.9850    0.9850      2000

Confusion Matrix:
 [[ 694   18]
 [  12 1276]]


In [46]:
print("score of training set: {:.3f}".format(etc.score(x_train_scaled, y_train)))
print("score of TEst set: {:.3f}".format(etc.score(x_test_scaled, y_test)))

score of training set: 1.000
score of TEst set: 0.985


In [47]:
#XG boost
from xgboost import XGBClassifier

xbc= XGBClassifier(random_state = 1)

xbc.fit(x_train_scaled, y_train)

XGBClassifier(random_state=1)

In [48]:
xbc_pred = xbc.predict(x_test_scaled)

In [49]:
#MMP XGB Classifier
#model accuracy
xbc_accuracy = accuracy_score(y_test, xbc_pred)
print('Accuracy: {}'.format(round(xbc_accuracy*100), 2))

#precision
xbc_precision = precision_score(y_test, xbc_pred, pos_label='stable')
print('Precision: {}'.format(round(xbc_precision*100), 2))  

#recall
xbc_recall = recall_score(y_test, xbc_pred, pos_label='stable')
print('Recall: {}'.format(round(xbc_recall*100), 2))

#F1 score
xbc_f1 = f1_score(y_test, xbc_pred, pos_label='stable')
print('F1: {}'.format(round(xbc_f1*100), 2))

#classification report
print('Classification Report:\n', classification_report(y_test,xbc_pred, digits =4))

#confusion matrix
c_cnf_mat = confusion_matrix(y_test, xbc_pred)
print('Confusion Matrix:\n', xbc_cnf_mat)

Accuracy: 100
Precision: 100
Recall: 100
F1: 100
Classification Report:
               precision    recall  f1-score   support

      stable     0.9986    1.0000    0.9993       712
    unstable     1.0000    0.9992    0.9996      1288

    accuracy                         0.9995      2000
   macro avg     0.9993    0.9996    0.9995      2000
weighted avg     0.9995    0.9995    0.9995      2000



NameError: ignored

In [50]:
from lightgbm import LGBMClassifier

lgbm= LGBMClassifier(random_state = 1)

#fit on train set
lgbm.fit(x_train_scaled, y_train)

LGBMClassifier(random_state=1)

In [51]:
lgbm_pred = lgbm.predict(x_test_scaled)

In [52]:
lgbm_accuracy = accuracy_score(y_test, lgbm_pred)
print('Accuracy: {}'.format(round(lgbm_accuracy*100), 2))


lgbm_precision = precision_score(y_test, lgbm_pred, pos_label='stable')
print('Precision: {}'.format(round(lgbm_precision*100), 2))  

lgbm_recall = recall_score(y_test, lgbm_pred, pos_label='stable')
print('Recall: {}'.format(round(lgbm_recall*100), 2))

lgbm_f1 = f1_score(y_test, lgbm_pred, pos_label='stable')
print('F1: {}'.format(round(lgbm_f1*100), 2))

print('Classification Report:\n', classification_report(y_test,lgbm_pred, digits =4))

lgbm_cnf_mat = confusion_matrix(y_test, lgbm_pred)
print('Confusion Matrix:\n', lgbm_cnf_mat)

Accuracy: 100
Precision: 99
Recall: 100
F1: 99
Classification Report:
               precision    recall  f1-score   support

      stable     0.9930    0.9958    0.9944       712
    unstable     0.9977    0.9961    0.9969      1288

    accuracy                         0.9960      2000
   macro avg     0.9953    0.9960    0.9956      2000
weighted avg     0.9960    0.9960    0.9960      2000

Confusion Matrix:
 [[ 709    3]
 [   5 1283]]


In [53]:
# improvement in ET classisfier
n_estimators = [50, 100, 300, 500, 1000]

min_samples_split = [2, 3, 5, 7, 9]

min_samples_leaf = [1, 2, 4, 6, 8]

max_features = ['auto', 'sqrt', 'log2', None] 

hyperparameter_grid = {'n_estimators': n_estimators,

                       'min_samples_leaf': min_samples_leaf,

                       'min_samples_split': min_samples_split,

                       'max_features': max_features}

In [54]:
from sklearn.model_selection import RandomizedSearchCV

randomcv = RandomizedSearchCV(estimator = etc, 
                              param_distributions = hyperparameter_grid, cv=5, n_iter=10, scoring = 'accuracy', n_jobs = -1, verbose = 1,
                              random_state = 1)

In [55]:
search = randomcv.fit(x_train_scaled, y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


In [56]:
search.best_params_

{'max_features': None,
 'min_samples_leaf': 8,
 'min_samples_split': 2,
 'n_estimators': 1000}

In [58]:
importance = etc.feature_importances_

In [59]:
for i,v in enumerate(importance):
	print('Feature: %0d, Score: %.5f' % (i,v))

Feature: 0, Score: 0.05919
Feature: 1, Score: 0.05669
Feature: 2, Score: 0.05509
Feature: 3, Score: 0.01821
Feature: 4, Score: 0.01875
Feature: 5, Score: 0.01886
Feature: 6, Score: 0.01848
Feature: 7, Score: 0.03872
Feature: 8, Score: 0.04585
Feature: 9, Score: 0.04461
Feature: 10, Score: 0.04357
Feature: 11, Score: 0.58200


In [60]:
x_train_scaled.head()

tau2      tau3      tau4        p1        p2        p3        p4  \
0 -0.986042  0.650447  1.547527 -0.291490  0.061535  1.293862 -0.845074   
1  0.089437  1.035079 -1.641494  0.619865 -0.067235 -1.502925  0.486613   
2  1.298418 -0.502536  1.166046 -0.180521  0.490603  0.682560 -0.855302   
3  0.529920  1.299657 -1.141975 -0.812854 -0.763632  1.521579  0.658780   
4 -1.425627  0.312300  0.919137 -1.614296  0.760315  1.422019  0.639243   

         g1        g2        g3        g4      stab  
0  0.160918  0.339859  0.585568  0.492239  0.966192  
1 -0.293143 -1.558488  1.429649 -1.443521  0.056564  
2  1.399350  1.451534 -1.045743  0.492489  0.150532  
3 -0.958319  1.361958  1.604140  0.275303  1.167671  
4  1.676895  0.695660  1.137504 -1.312575  0.826921

In [61]:
search.best_score_

0.9998750000000001

In [62]:
etc2 = ExtraTreesClassifier(max_features = None, 
                            min_samples_leaf= 8,
                            min_samples_split= 2,
                            n_estimators= 1000, 
                            random_state = 1)
etc2.fit(x_train_scaled, y_train)

ExtraTreesClassifier(max_features=None, min_samples_leaf=8, n_estimators=1000,
                     random_state=1)

In [63]:
etc2_pred = etc2.predict(x_test_scaled)

In [64]:
print('Classification Report:\n', classification_report(y_test,etc2_pred, digits =4))

Classification Report:
               precision    recall  f1-score   support

      stable     0.9986    1.0000    0.9993       712
    unstable     1.0000    0.9992    0.9996      1288

    accuracy                         0.9995      2000
   macro avg     0.9993    0.9996    0.9995      2000
weighted avg     0.9995    0.9995    0.9995      2000

